'use client'
import { useEffect, useState } from 'react'
import { Check, FileText, Plus, RefreshCw } from 'lucide-react'
import type { CaseRecord } from '../lib/repositories/cases'
import type { CaseIntent, Locale } from '../lib/supabase/database'
import { caseStatusLabel } from '../lib/case-copy'

const copy: Record<Locale, { title: string; subtitle: string; create: string; empty: string; emptyText: string; open: string; save: string; titleField: string; login: string; error: string; configured: string }> = {
  bg:{title:'Моите случаи',subtitle:'Данните се пазят в Supabase и са видими само за вас.',create:'Създай случай',empty:'Все още няма случаи.',emptyText:'Създайте първия случай след като добавите документ или въпрос.',open:'Отвори',save:'Запази',titleField:'Заглавие',login:'Влезте в профила си, за да запазвате случаи.',error:'Възникна грешка.',configured:'Supabase не е конфигуриран.'},
  de:{title:'Meine Vorgänge',subtitle:'Ihre Daten werden in Supabase gespeichert und bleiben privat.',create:'Vorgang erstellen',empty:'Noch keine Vorgänge.',emptyText:'Erstellen Sie den ersten Vorgang nach einem Dokument oder Anliegen.',open:'Öffnen',save:'Speichern',titleField:'Titel',login:'Melden Sie sich an, um Vorgänge zu speichern.',error:'Ein Fehler ist aufgetreten.',configured:'Supabase ist nicht konfiguriert.'},
  ru:{title:'Мои дела',subtitle:'Данные хранятся в Supabase и доступны только вам.',create:'Создать дело',empty:'Дел пока нет.',emptyText:'Создайте первое дело после добавления документа или вопроса.',open:'Открыть',save:'Сохранить',titleField:'Название',login:'Войдите, чтобы сохранять дела.',error:'Произошла ошибка.',configured:'Supabase не настроен.'},
  pl:{title:'Moje sprawy',subtitle:'Dane są przechowywane w Supabase i widoczne tylko dla Ciebie.',create:'Utwórz sprawę',empty:'Brak spraw.',emptyText:'Utwórz pierwszą sprawę po dodaniu dokumentu lub pytania.',open:'Otwórz',save:'Zapisz',titleField:'Tytuł',login:'Zaloguj się, aby zapisywać sprawy.',error:'Wystąpił błąd.',configured:'Supabase nie jest skonfigurowany.'},
  sr:{title:'Моји предмети',subtitle:'Подаци се чувају у Supabase-у и видљиви су само вама.',create:'Направи предмет',empty:'Нема предмета.',emptyText:'Направите први предмет након додавања документа или питања.',open:'Отвори',save:'Сачувај',titleField:'Наслов',login:'Пријавите се да бисте чували предмете.',error:'Дошло је до грешке.',configured:'Supabase није подешен.'},
  ro:{title:'Cazurile mele',subtitle:'Datele sunt stocate în Supabase și sunt vizibile doar pentru dvs.',create:'Creează caz',empty:'Nu există cazuri.',emptyText:'Creați primul caz după adăugarea unui document sau a unei întrebări.',open:'Deschide',save:'Salvează',titleField:'Titlu',login:'Autentificați-vă pentru a salva cazuri.',error:'A apărut o eroare.',configured:'Supabase nu este configurat.'},
}

export function CaseWorkspace({ locale, fileName }: { locale: Locale; fileName?: string }) {
  const t = copy[locale]; const [cases, setCases] = useState<CaseRecord[]>([]); const [selected, setSelected] = useState<CaseRecord | null>(null); const [title, setTitle] = useState(fileName ?? ''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [configured, setConfigured] = useState(true)
  async function load() { setLoading(true); const response = await fetch('/api/cases', { cache:'no-store' }); const json = await response.json().catch(() => ({})); setConfigured(json.configured !== false); if (response.ok) setCases(json.cases ?? []); else if (response.status !== 401) setError(json.error ?? t.error); setLoading(false) }
  // The initial request synchronizes this client component with the remote repository.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [])
  async function createCase() { setBusy(true); setError(''); const response = await fetch('/api/cases', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ title: title.trim() || 'KintexBG case', intent:'explanation' as CaseIntent, ui_locale:locale, conversation_locale:locale }) }); const json = await response.json().catch(() => ({})); if (!response.ok) setError(response.status === 401 ? t.login : json.error ?? t.error); else { setTitle(''); await load() }; setBusy(false) }
  async function openCase(id: string) { setError(''); const response = await fetch(`/api/cases/${id}`, { cache:'no-store' }); const json = await response.json().catch(() => ({})); if (!response.ok) setError(json.error ?? t.error); else { setSelected(json.case); setTitle(json.case.title) } }
  async function saveCase() { if (!selected) return; setBusy(true); const response = await fetch(`/api/cases/${selected.id}`, { method:'PATCH', headers:{'content-type':'application/json'}, body:JSON.stringify({ title }) }); const json = await response.json().catch(() => ({})); if (!response.ok) setError(json.error ?? t.error); else { setSelected(json.case); await load() }; setBusy(false) }
  return <section className="mt-8 rounded-2xl border bg-card p-5 shadow-sm sm:p-8"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{t.title}</h2><p className="mt-1 text-sm text-muted-foreground">{t.subtitle}</p></div><button onClick={() => void createCase()} disabled={busy || loading} className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-60"><Plus className="size-4" />{t.create}</button></div>{!configured && <p className="mb-4 rounded-lg border border-primary/20 bg-primary/5 p-3 text-sm text-muted-foreground">{t.configured}</p>}{error && <p role="alert" className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{selected && <div className="mb-5 rounded-xl border border-primary/30 bg-primary/5 p-4"><label className="block text-sm font-medium">{t.titleField}<input value={title} onChange={e => setTitle(e.target.value)} maxLength={200} className="mt-2 w-full rounded-lg border bg-background px-3 py-2" /></label><div className="mt-3 flex items-center gap-2"><button onClick={() => void saveCase()} disabled={busy} className="rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground">{t.save}</button><span className="text-xs text-muted-foreground">{caseStatusLabel(locale, selected.status)}</span></div></div>}{loading ? <div className="flex items-center gap-2 text-sm text-muted-foreground"><RefreshCw className="size-4 animate-spin" />…</div> : cases.length ? <div className="grid gap-3 sm:grid-cols-2">{cases.map(item => <button key={item.id} onClick={() => void openCase(item.id)} className="rounded-xl border p-4 text-left transition hover:border-primary/40"><div className="flex items-start justify-between gap-2"><FileText className="size-5 text-primary" /><span className="rounded-full bg-secondary px-2 py-1 text-[10px] font-semibold text-primary">{caseStatusLabel(locale, item.status)}</span></div><p className="mt-3 font-medium">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(item.created_at).toLocaleDateString(locale)}</p></button>)}</div> : <div className="rounded-xl border border-dashed p-8 text-center"><Check className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 font-medium">{t.empty}</p><p className="mt-1 text-sm text-muted-foreground">{t.emptyText}</p></div>}</section>
}
