import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { detailCopy } from '../../../lib/case-detail-copy'
import { authCopy } from '../../../lib/auth-copy'
import { locales } from '../../../lib/locales'
import type { Locale } from '../../../lib/supabase/database'
import { createClient } from '../../../lib/supabase/server'
import { syncProfile, signOut } from '../../actions/auth'

export default async function SettingsPage({ params }: { params: Promise<{ locale:string }> }) { const { locale } = await params; if (!locales.includes(locale as Locale)) notFound(); const supabase = await createClient(); if (!supabase) return <main className="p-8">{authCopy[locale as Locale].setup}</main>; const { data:{ user } } = await supabase.auth.getUser(); if (!user) redirect(`/${locale}/login`); const { data: profile } = await supabase.from('profiles').select('display_name, locale, conversation_locale, output_locale').eq('id', user.id).maybeSingle(); const t = detailCopy[locale as Locale]; return <main className="min-h-screen bg-muted px-4 py-10"><section className="mx-auto max-w-2xl rounded-2xl border bg-card p-6 shadow-sm"><Link href={`/${locale}/dashboard`} className="text-sm text-primary hover:underline">← {t.back}</Link><h1 className="mt-5 text-2xl font-semibold">{t.settings}</h1><p className="mt-2 text-sm text-muted-foreground">{t.privacy}</p><form action={async (form: FormData) => { 'use server'; await syncProfile({ locale:String(form.get('locale') || 'bg'), conversationLocale:String(form.get('conversation_locale') || 'bg'), outputLocale:String(form.get('output_locale') || 'de'), displayName:String(form.get('display_name') || '') }) }} className="mt-6 space-y-4"><label className="block text-sm font-medium">{t.displayName}<input name="display_name" defaultValue={profile?.display_name || ''} maxLength={120} className="mt-2 w-full rounded-lg border bg-background px-3 py-2" /></label><LanguageSelect name="locale" label={t.interfaceLanguage} value={profile?.locale || locale} /><LanguageSelect name="conversation_locale" label={t.conversationLanguage} value={profile?.conversation_locale || locale} /><LanguageSelect name="output_locale" label={t.outputLanguage} value={profile?.output_locale || 'de'} /><p className="text-sm text-muted-foreground">{user.email}</p><button className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{t.save}</button></form><form action={signOut} className="mt-4"><button className="rounded-lg border px-4 py-2 text-sm">{authCopy[locale as Locale].signOut}</button></form></section></main> }
function LanguageSelect({ name, label, value }: { name:string; label:string; value:string }) { return <label className="block text-sm font-medium">{label}<select name={name} defaultValue={value} className="mt-2 w-full rounded-lg border bg-background px-3 py-2">{locales.map(item => <option key={item} value={item}>{item.toUpperCase()}</option>)}</select></label> }
