import type { Locale } from './supabase/database'

const keys = ['home','cases','documents','drafts','settings','help','platform','language','manual','recipient','subject','request','upload','limit','open','export','history','facts','newCase','approved','translationUnavailable','confirm','retry','network','saveFirst','saved','helpText'] as const
type Copy = Record<typeof keys[number], string>
const values: Record<Locale, string[]> = {
  bg: ['Нов случай','Моите случаи','Документи','Чернови','Настройки','Помощ','Към KintexBG','Език','Ръчен режим — без OCR и AI превод. Въведете темата и искането на немски.','Получател','Тема на немски','Искане на немски','Качи документ','PDF, JPG, PNG · до 4 MB','Отвори','Изтегли TXT','Версии','Потвърдени факти','Нов случай','Одобрена','Преводът не е наличен. Немският текст не е превод на вашия език.','Проверих точната чернова, получателя и приложенията.','Опитай отново','Неуспешна връзка. Опитайте отново.','Първо запазете случая.','Запазено','Създайте случай, качете документ при нужда и въведете потвърдените данни. Запазете фактите, създайте чернова и я проверете преди одобрение. Нищо не се изпраща автоматично. TXT export не е PDF подпис.'],
  de: ['Neuer Vorgang','Meine Vorgänge','Dokumente','Entwürfe','Einstellungen','Hilfe','Zu KintexBG','Sprache','Manueller Modus — ohne OCR oder KI-Übersetzung. Betreff und Anliegen auf Deutsch eingeben.','Empfänger','Betreff auf Deutsch','Anliegen auf Deutsch','Dokument hochladen','PDF, JPG, PNG · bis 4 MB','Öffnen','TXT herunterladen','Versionen','Bestätigte Fakten','Neuer Vorgang','Freigegeben','Keine Übersetzung verfügbar. Der deutsche Text ist keine Übersetzung in Ihre Sprache.','Ich habe diesen Entwurf, den Empfänger und die Anlagen geprüft.','Erneut versuchen','Verbindung fehlgeschlagen. Bitte erneut versuchen.','Speichern Sie zuerst den Vorgang.','Gespeichert','Vorgang erstellen, bei Bedarf ein Dokument hochladen und bestätigte Angaben eingeben. Fakten speichern, Entwurf erstellen und vor der Freigabe prüfen. Es wird nichts automatisch versendet. TXT-Export ist keine PDF-Signatur.'],
  ru: ['Новое дело','Мои дела','Документы','Черновики','Настройки','Помощь','К KintexBG','Язык','Ручной режим — без OCR и ИИ-перевода. Введите тему и запрос на немецком.','Получатель','Тема на немецком','Запрос на немецком','Загрузить документ','PDF, JPG, PNG · до 4 МБ','Открыть','Скачать TXT','Версии','Подтверждённые факты','Новое дело','Одобрено','Перевод недоступен. Немецкий текст не является переводом на ваш язык.','Я проверил этот черновик, получателя и приложения.','Повторить','Ошибка соединения. Повторите попытку.','Сначала сохраните дело.','Сохранено','Создайте дело, при необходимости загрузите документ и введите подтверждённые данные. Сохраните факты, создайте черновик и проверьте перед одобрением. Автоматической отправки нет. Экспорт TXT не является подписью PDF.'],
  pl: ['Nowa sprawa','Moje sprawy','Dokumenty','Projekty','Ustawienia','Pomoc','Do KintexBG','Język','Tryb ręczny — bez OCR i tłumaczenia AI. Wpisz temat i prośbę po niemiecku.','Odbiorca','Temat po niemiecku','Prośba po niemiecku','Prześlij dokument','PDF, JPG, PNG · do 4 MB','Otwórz','Pobierz TXT','Wersje','Potwierdzone fakty','Nowa sprawa','Zatwierdzono','Tłumaczenie niedostępne. Tekst niemiecki nie jest tłumaczeniem na Twój język.','Sprawdziłem ten projekt, odbiorcę i załączniki.','Spróbuj ponownie','Błąd połączenia. Spróbuj ponownie.','Najpierw zapisz sprawę.','Zapisano','Utwórz sprawę, w razie potrzeby prześlij dokument i wpisz potwierdzone dane. Zapisz fakty, utwórz projekt i sprawdź go przed zatwierdzeniem. Nic nie jest wysyłane automatycznie. Eksport TXT nie jest podpisem PDF.'],
  sr: ['Нови предмет','Моји предмети','Документи','Нацрти','Подешавања','Помоћ','Ка KintexBG','Језик','Ручни режим — без OCR и AI превода. Унесите тему и захтев на немачком.','Прималац','Тема на немачком','Захтев на немачком','Отпреми документ','PDF, JPG, PNG · до 4 MB','Отвори','Преузми TXT','Верзије','Потврђене чињенице','Нови предмет','Одобрено','Превод није доступан. Немачки текст није превод на ваш језик.','Проверио сам овај нацрт, примаоца и прилоге.','Покушај поново','Веза није успела. Покушајте поново.','Прво сачувајте предмет.','Сачувано','Направите предмет, по потреби отпремите документ и унесите потврђене податке. Сачувајте чињенице, направите нацрт и проверите га пре одобрења. Нема аутоматског слања. TXT извоз није PDF потпис.'],
  ro: ['Caz nou','Cazurile mele','Documente','Proiecte','Setări','Ajutor','La KintexBG','Limbă','Mod manual — fără OCR sau traducere AI. Introduceți subiectul și cererea în germană.','Destinatar','Subiect în germană','Cerere în germană','Încarcă document','PDF, JPG, PNG · până la 4 MB','Deschide','Descarcă TXT','Versiuni','Fapte confirmate','Caz nou','Aprobat','Traducerea nu este disponibilă. Textul german nu este o traducere în limba dvs.','Am verificat acest proiect, destinatarul și anexele.','Încearcă din nou','Conexiune eșuată. Încercați din nou.','Salvați mai întâi cazul.','Salvat','Creați un caz, încărcați un document dacă este necesar și introduceți datele confirmate. Salvați faptele, creați un proiect și verificați-l înainte de aprobare. Nimic nu se trimite automat. Exportul TXT nu este o semnătură PDF.'],
}
export const workspaceCopy = Object.fromEntries(Object.entries(values).map(([locale, strings]) => [locale, Object.fromEntries(keys.map((key, i) => [key, strings[i]]))])) as Record<Locale, Copy>

export const aiCopy: Record<Locale, { notice: string; subject: string; request: string }> = {
  bg: { notice: 'AI чернова и превод чрез Groq. При „Създай чернова“ потвърдените полета се изпращат на Groq. Файловете не се изпращат и OCR не е наличен. Проверете резултата.', subject: 'Тема', request: 'Какво искате да напишете?' },
  de: { notice: 'KI-Entwurf und Übersetzung mit Groq. Beim Erstellen werden die bestätigten Felder an Groq gesendet. Keine Dateiübertragung, kein OCR. Ergebnis bitte prüfen.', subject: 'Betreff', request: 'Was möchten Sie schreiben?' },
  ru: { notice: 'ИИ-черновик и перевод через Groq. При создании подтверждённые поля передаются Groq. Файлы не отправляются, OCR недоступен. Проверьте результат.', subject: 'Тема', request: 'Что вы хотите написать?' },
  pl: { notice: 'Projekt AI i tłumaczenie przez Groq. Utworzenie projektu wysyła potwierdzone pola do Groq. Pliki nie są przesyłane, OCR niedostępny. Sprawdź wynik.', subject: 'Temat', request: 'Co chcesz napisać?' },
  sr: { notice: 'AI нацрт и превод преко Groq. Креирање шаље потврђена поља у Groq. Датотеке се не шаљу, OCR није доступан. Проверите резултат.', subject: 'Тема', request: 'Шта желите да напишете?' },
  ro: { notice: 'Proiect AI și traducere prin Groq. Crearea trimite câmpurile confirmate către Groq. Fișierele nu sunt trimise, OCR indisponibil. Verificați rezultatul.', subject: 'Subiect', request: 'Ce doriți să scrieți?' },
}
